name: mario_touch_adventure
description: "Un juego de plataformas táctil inspirado en Mario con física realista y efectos visuales profesionales."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI y Animaciones
  flutter_animate: ^4.5.2
  flutter_staggered_animations: ^1.1.1
  sizer: ^2.0.15
  
  # Estado y Gestión
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  
  # Audio
  audioplayers: ^5.2.1
  
  # Utilidades
  equatable: ^2.0.7
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/audio/
    - assets/animations/