name: mario_touch_adventure
description: A professional Mario-style touch adventure game with enhanced gameplay mechanics and realistic physics.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:       # 🚨 CRITICAL: Required for every Flutter project - DO NOT REMOVE
    sdk: flutter # 🚨 CRITICAL: Required for every Flutter project - DO NOT REMOVE
  
  # 🚨 CRITICAL: Core UI and responsive design - DO NOT REMOVE OR MODIFY
  sizer: ^2.0.15              # Required for responsive design system
  flutter_svg: ^2.0.9        # Required for SVG icon support
  google_fonts: ^6.1.0       # Required for typography (replaces local fonts)
  shared_preferences: ^2.2.2 # Required for local data storage
  web: ^1.1.1
  
  # Professional Gaming Dependencies
  audioplayers: ^5.2.1        # Professional audio system
  flame: ^1.14.0              # Game engine for physics and animations
  flame_audio: ^2.1.8         # Audio integration for Flame
  rive: ^0.12.4               # Advanced animations and effects
  lottie: ^2.7.0              # Professional animations
  flutter_staggered_animations: ^1.1.1  # Staggered animations
  confetti: ^0.7.0            # Celebration effects
  flutter_animate: ^4.2.0     # Modern animation system
  
  # Enhanced UI/UX
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.1.4
  dio: ^5.4.0
  fluttertoast: ^8.2.4
  fl_chart: ^0.65.0
  universal_html: ^2.2.4
  
  # Performance and State Management
  provider: ^6.1.1            # State management
  get_it: ^7.6.4              # Dependency injection
  hive: ^2.2.3                # Fast local storage
  hive_flutter: ^1.1.0        # Flutter integration for Hive

dev_dependencies:
  flutter_test:    # 🚨 CRITICAL: Required for Flutter project testing - DO NOT REMOVE
    sdk: flutter   # 🚨 CRITICAL: Required for Flutter project testing - DO NOT REMOVE
  flutter_lints: ^5.0.0 # 🚨 CRITICAL: Required for code quality - DO NOT REMOVE
  hive_generator: ^2.0.1      # Code generation for Hive
  build_runner: ^2.4.7        # Code generation

flutter:
  uses-material-design: true # 🚨 CRITICAL: Required for Material icon font - DO NOT REMOVE
  assets:
    - assets/
    - assets/images/
    - assets/audio/
    - assets/animations/
  # 🚨 CRITICAL ASSET MANAGEMENT RULES:
  # - DO NOT ADD NEW ASSET DIRECTORIES (assets/svg/, assets/icons/, etc.)
  # - ONLY USE EXISTING AND ITEMS AVAILABLE IN THE DIRECTORIES LISTED ABOVE (assets/, assets/images/)
  
  # 🚨 CRITICAL FONTS RULE: 
  # - THIS PROJECT USES GOOGLE FONTS INSTEAD OF LOCAL FONTS
  # - DO NOT ADD ANY LOCAL FONTS SECTION OR FONT FILES